[[module]]
name = "test"
[[module.file]]
name = "src/script/test.as"
[[module.function]]
name = "printHello"

[[module]]
name = "default"
[[module.file]]
name = "src/script/default.as"
[[module.function]]
name = "onCreated"
[[module.function]]
name = "update"
[[module.function]]
name = "onDestroyed"

[[module]]
name = "component"
[[module.file]]
name = "src/script/component.as"
[[module.file]]
name = "src/script/movable.as"
[[module.function]]
name = "fake"
