[[module]]
name = "test"
file = [
    "src/script/test.as"
]
# function = [
#     "printHello"
# ]

[[module]]
name = "default"
file = [
    "src/script/default.as"
]
# function = [
#     "onCreated",
#     "update",
#     "onDestroyed"
# ]

[[module]]
name = "component"
file = [
    "src/script/component.as",
    "src/script/movable.as"
]
