[[entities]]
name = "Dummy"
[entities.health]
max = 100
regen = 2.0
[entities.transform]
position = [0.0, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0, 1.0]
scale    = [1.0, 1.0, 1.0]
[entities.model]
mesh = "Sphere"
texture = "asset/world_map.jpg"
shader = "default"
[entities.input]
[[entities.input.map]]
trigger = "Keyboard.Up.Held"
action = "default.onInputEvent"
[[entities.input.map]]
trigger = "Keyboard.Left.Held"
action = "default.onInputEvent"
[[entities.input.map]]
trigger = "Keyboard.Down.Held"
action = "default.onInputEvent"
[[entities.input.map]]
trigger = "Keyboard.Right.Held"
action = "default.onInputEvent"

[[entities]]
name = "Cuby1"
[entities.transform]
position = [-1.5, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0, 1.0]
scale    = [0.5, 0.5, 0.5]
[entities.model]
mesh = "Cube"
texture = "asset/metal_logo.png"
shader = "default"

[[entities]]
name = "Cuby2"
[entities.transform]
position = [1.5, -0.5, 0.0]
rotation = [0.0, 0.0, 0.0, 1.0]
scale    = [0.5, 0.5, 0.5]
[entities.model]
mesh = "Cube"
texture = "asset/metal_logo.png"
shader = "default"

[[entities]]
name = "Cuby3"
[entities.transform]
position = [-0.5, 0.5, 1.5]
rotation = [0.0, 0.0, 0.0, 1.0]
scale    = [0.5, 0.5, 0.5]
[entities.model]
mesh = "Cube"
texture = "asset/metal_logo.png"
shader = "default"

[[entities]]
name = "Cuby4"
[entities.transform]
position = [1.0, -0.5, 1.0]
rotation = [0.0, 0.0, 0.0, 1.0]
scale    = [0.5, 0.5, 0.5]
[entities.model]
mesh = "Cube"
texture = "asset/metal_logo.png"
shader = "default"

[[entities]]
name = "Camera0"
[entities.transform]
position = [0.0, 5.0, -4.5]
rotation = [0.3826834, 0.0, 0.0, 0.9238795]
scale    = [1.0, 1.0, 1.0]
[entities.camera]
type       = "MainCamera"
fov        = 45.0
nearPlane  = 0.1
farPlane   = 100.0
projection = "perspective"

[[entities]]
name = "Camera1"
[entities.transform]
position = [8.0, 8.0, 0.0]
rotation = [0.0, 0.0, 0.0, 1.0]
scale    = [1.0, 1.0, 1.0]
[entities.camera]
type       = "SubCamera"
fov        = 70.0
nearPlane  = 0.1
farPlane   = 50.0
projection = "perspective"
